baseURL = "https://hypnotherapyhealthcare.co.uk/"
googleAnalytics = "UA-35915992-3"
languageCode = "en-gb"
theme = "minimal"
title = "Coming Soon"
[[menu.icon]]
name = "envelope-o"
url = "mailto:rebekah@hypnotherapyhealthcare.co.uk"
weight = 1
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "How it Works"
url = "/how-it-works"
weight = 2
[[menu.main]]
name = "What is on Offer"
url = "/what-is-on-offer"
weight = 3
[[menu.main]]
name = "My Story"
url = "/my-story"
weight = 4
[[menu.footer]]
name = "Certified Hypnotherapist"
url = "/img/clhyp_logo.png"
weight = 1
[[menu.footer]]
name = "EMCC Accredited Coach / Mentor"
url = "/img/emcc-logo.png"
weight = 2
[[menu.footer]]
name = "National Council of Psychotherapists"
url = "/img/ncp_logo.png"
weight = 3
[[menu.footer]]
name = "Complementary & Natural Healthcare Council"
url = "/img/cnhc_logo.jpg"
weight = 4
[params]
accent = "#00A499"
author = "Dr Rebekah Gibbons"
backgroundColor = "white"
description = "Hypnotherapy Healthcare"
font = "Raleway"
profilePic = "img/logo.png"
showBorder = true