baseURL = "https://hypnotherapyhealthcare.co.uk/"
googleAnalytics = "UA-35915992-3"
languageCode = "en-gb"
theme = "minimal"
title = "Coming Soon"
[[menu.icon]]
name = "envelope-o"
url = "mailto:rebekah@hypnotherapyhealthcare.co.uk"
weight = 1
[[menu.icon]]
name = "twitter"
url = "https://twitter.com/gibbons_rebekah/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
accent = "#00A499"
author = "Dr Rebekah Gibbons"
backgroundColor = "white"
description = "Hypnotherapy Healthcare"
font = "Raleway"
profilePic = "img/logo.png"
showBorder = true