baseURL = "https://hypnotherapyhealthcare.co.uk/"
googleAnalytics = "UA-35915992-3"
languageCode = "en-gb"
theme = "minimal"
title = "Coming Soon"
[[menu.icon]]
name = "envelope-o"
url = "mailto:rebekah@hypnotherapyhealthcare.co.uk"
weight = 1
[[menu.icon]]
name = "twitter"
url = "https://twitter.com/gibbons_rebekah/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "How it Works"
url = "/how-it-works"
weight = 2
[[menu.main]]
name = "What is on Offer"
url = "/what-is-on-offer"
weight = 3
[[menu.main]]
name = "My Story"
url = "/my-story"
weight = 4
[[menu.main]]
name = "Testimonials"
url = "/testimonials"
weight = 5
[[menu.footer]]
url = "/img/RTT_CHYP_Logo.png"
[[menu.footer]]
url = "/img/RTT_Therapist_Rounded_Logo.png"
[params]
accent = "#00A499"
author = "Dr Rebekah Gibbons"
backgroundColor = "white"
description = "Hypnotherapy Healthcare"
font = "Raleway"
profilePic = "img/logo.png"
showBorder = true